image: python:3-alpine

pages:
  script:
  - pip install monopati
  - monopati render
  - cp -r extras/. public
  - cd public/category/libre/feed/atom/
  - ln -s ../../../../tag/opensource/feed.xml index.html
  - cd ../../../../../
  artifacts:
    paths:
    - public
  only:
  - master
