image: python:3-alpine

pages:
  script:
  - pip install -r requirements.txt
  - ./monopati.py
  - mkdir public
  - cp -r static 20* category tag pub *.html *.ico *.txt *.xml public
  artifacts:
    paths:
    - public
  only:
  - master
