image: python:3-alpine

pages:
  script:
  - apk add zlib-dev libjpeg-turbo-dev gcc musl-dev
  - pip install monopati sigal
  - monopati render
  - sigal build
  - cp -r extras/. public
  - cd public/category/libre/feed/atom/
  - ln -s ../../../../tag/opensource/feed.xml index.html
  - cd ../../../../../
  artifacts:
    paths:
    - public
  only:
  - master
