image: ubuntu:24.04

pages:
  script:
  - apt update
  - DEBIAN_FRONTEND=noninteractive apt install -y wget git python3 python3-pip nodejs npm libgomp1 zopfli libpng-dev libjpeg-turbo8 libwebp-dev libtiff-dev liblcms2-2 x265 libde265-0 libheif1 ffmpeg libexif12 imagemagick graphicsmagick gifsicle zip
  - pip install --break-system-packages monopati
  - npm install -g thumbsup
  - monopati render
  - cp -r extras/. public
  - cd public/category/libre/feed/atom/
  - ln -s ../../../../tag/opensource/feed.xml index.html
  - cd ../../../../../
  - wget --recursive --no-parent https://${PHOTO_URI}
  - mv /${PHOTO_URI} photos/
  - CHECK=$(du -sb photos/ | cut -f1); if [ "$CHECK" -lt 500000 ]; then exit 1; fi;
  - thumbsup --config thumbsup.json --theme-style static/css/app.css
  - ./bin/photos-theme.sh
  artifacts:
    paths:
    - public
  only:
  - main
