sitename: nikos.roussos
author: Nikos Roussos
rooturl: https://www.roussos.cc/
license: <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">Creative Commons Attribution-ShareAlike</a>
